FROM golang:1.24 AS build

RUN go install github.com/air-verse/air@v1.52.3

# Install buf and Go plugins
RUN go install github.com/bufbuild/buf/cmd/buf@latest && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# Set up directory structure to match local
WORKDIR /grpc-sample

# Copy proto files and configuration
COPY proto /grpc-sample/proto

# Initialize proto module
WORKDIR /grpc-sample/proto
RUN go mod download

# Generate proto files using buf
RUN buf generate

# Copy service files
WORKDIR /grpc-sample/services/account
COPY services/account/go.mod services/account/go.sum ./
RUN go mod download

COPY services/account/ ./

CMD ["air", "-c", ".air.toml"]