FROM golang:1.24 AS build

RUN go install github.com/air-verse/air@v1.52.3

# Set up directory structure to match local
WORKDIR /grpc-sample

# Copy proto files (including generated code from host)
COPY proto /grpc-sample/proto

# Initialize proto module
WORKDIR /grpc-sample/proto
RUN go mod download

# Copy graphql service files
WORKDIR /grpc-sample/services/graphql
COPY services/graphql/go.mod services/graphql/go.sum ./

# Copy all service files before go mod download
COPY services/graphql/ ./

# Download dependencies and tidy
RUN go mod download && go mod tidy

CMD ["air", "-c", ".air.toml"]